// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Application = {
    Models: {},
    Collections: {},
    Views: {},
    router: {}
  };

  Application.Models.Post = (function(_super) {

    __extends(Post, _super);

    function Post() {
      return Post.__super__.constructor.apply(this, arguments);
    }

    Post.prototype.el = "article";

    Post.prototype.tagName = "article";

    Post.prototype["class"] = "post";

    Post.prototype.template = $('#post_template');

    Post.prototype.render = function() {
      var compiled;
      compiled = _.template(this.template);
      return this.$el.html(compiled(this.model));
    };

    return Post;

  })(Backbone.Model);

  Application.Collection.Posts = (function(_super) {

    __extends(Posts, _super);

    function Posts() {
      return Posts.__super__.constructor.apply(this, arguments);
    }

    Posts.prototype.model = Application.Models.Post;

    return Posts;

  })(Backbone.Collection);

  Application.router = (function(_super) {

    __extends(router, _super);

    function router() {
      return router.__super__.constructor.apply(this, arguments);
    }

    router.prototype.routes = {
      "/:year/:month/:day/:slug": "post"
    };

    router.prototype.post = function(year, month, day, slug) {
      return console.log(year, month, day, slug);
    };

    return router;

  })(Backbone.Router);

}).call(this);
