parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.json'

plugins:
  - json
  - '@typescript-eslint'

extends: 
  - "plugin:json/recommended"
  - "plugin:@typescript-eslint/recommended"

overrides:
  - files: '*.json'
    extends:
      - "plugin:json/recommended"
    parserOptions:
      project: null
  - files: '*.mjs'
    parser: espree
    parserOptions:
      ecmaVersion: 2020
      sourceType: module
      project: null