parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: './tsconfig.json'

plugins:
  - json
  - '@typescript-eslint'

extends: 
  - "plugin:json/recommended"
  - "plugin:@typescript-eslint/recommended"