inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - _site/**/*
    - node_modules/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Max: 10
