import bundleAnalyzer from '@next/bundle-analyzer';
import createMDX from '@next/mdx';

const withBundleAnalyzer = bundleAnalyzer({
  enabled: process.env.ANALYZE === 'true',
});

// Configure MDX for native .mdx file support
// Note: For remark/rehype plugin support with MDX, the markdown is processed
// at runtime via lib/markdown.ts which uses the full remark/rehype pipeline.
// This MDX config enables importing .mdx files as React components.
const withMDX = createMDX({
  extension: /\.mdx?$/,
});

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Enable MDX page extensions
  pageExtensions: ['js', 'jsx', 'md', 'mdx', 'ts', 'tsx'],
  // Output static site for GitHub Pages compatibility
  output: 'export',
  
  // Disable image optimization for static export
  // See: https://nextjs.org/docs/app/api-reference/components/image#unoptimized
  images: {
    unoptimized: true,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'avatars.githubusercontent.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'github.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'images.amazon.com',
        port: '',
        pathname: '/**',
      },
    ],
  },
  
  // Trailing slash for GitHub Pages compatibility
  // See: https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash
  trailingSlash: true,

  // Compiler options for production optimization
  // Remove console logs in production for cleaner output and reduced bundle size
  compiler: {
    removeConsole: process.env.NODE_ENV === 'production' ? {
      exclude: ['error', 'warn'],
    } : false,
  },

  // React strict mode for development best practices
  // See: https://nextjs.org/docs/app/api-reference/next-config-js/reactStrictMode
  reactStrictMode: true,

  // Sass options to silence deprecation warnings from dependencies (Bootstrap 5.3.x)
  // These will be fixed when Bootstrap migrates to the new Sass module system
  // See: https://sass-lang.com/d/import and https://sass-lang.com/d/color-functions
  sassOptions: {
    silenceDeprecations: ['import', 'global-builtin', 'color-functions'],
  },

  // Experimental features for performance optimization
  experimental: {
    // Optimize package imports for faster builds and smaller bundles
    // See: https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports
    optimizePackageImports: [
      '@fortawesome/fontawesome-svg-core',
      '@fortawesome/free-brands-svg-icons',
      '@fortawesome/free-regular-svg-icons',
      '@fortawesome/free-solid-svg-icons',
      '@fortawesome/react-fontawesome',
    ],
  },

  // Remove 'X-Powered-By: Next.js' header for security (reduce information disclosure)
  // See: https://nextjs.org/docs/app/api-reference/next-config-js/poweredByHeader
  poweredByHeader: false,

  // Legacy URL redirects from Jekyll
  // Note: redirects() is not supported with output: 'export'
  // These are handled via static HTML files generated by script/generate-redirects.mjs
  
  // Turbopack configuration (Next.js 16+ default)
  // Empty config to silence warning about webpack config
  turbopack: {},
  
  // Webpack configuration for better optimization (used in webpack mode only)
  webpack: (config, { dev, isServer }) => {
    // Optimize bundle size in production
    if (!dev && !isServer) {
      config.optimization = {
        ...config.optimization,
        usedExports: true,
      };
    }
    
    return config;
  },
};

// Compose configuration wrappers
// Order: innermost to outermost (MDX first, then Bundle Analyzer)
// MDX wrapper modifies pageExtensions and adds the MDX loader
// Bundle Analyzer wrapper adds optional bundle analysis support
export default withBundleAnalyzer(withMDX(nextConfig));
