/** @type {import('next').NextConfig} */
const nextConfig = {
  // Output static site for GitHub Pages compatibility
  output: 'export',
  
  // Disable image optimization for static export
  // See: https://nextjs.org/docs/app/api-reference/components/image#unoptimized
  images: {
    unoptimized: true,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'avatars.githubusercontent.com',
        port: '',
        pathname: '/**',
      },
    ],
  },
  
  // Trailing slash for GitHub Pages compatibility
  // See: https://nextjs.org/docs/app/api-reference/next-config-js/trailingSlash
  trailingSlash: true,

  // Compiler options for production optimization
  compiler: {
    // Remove console logs in production for better performance
    removeConsole: process.env.NODE_ENV === 'production' ? {
      exclude: ['error', 'warn'],
    } : false,
  },

  // React strict mode for development best practices
  // See: https://nextjs.org/docs/app/api-reference/next-config-js/reactStrictMode
  reactStrictMode: true,

  // Power preference for better performance
  // See: https://nextjs.org/docs/app/api-reference/next-config-js/poweredByHeader
  poweredByHeader: false,

  // Legacy URL redirects from Jekyll
  // Note: redirects() is not supported with output: 'export'
  // These are handled via static HTML files generated by script/generate-redirects.mjs
};

export default nextConfig;
