// Generated by CoffeeScript 1.4.0
(function() {
  var relative_time;

  relative_time = function(c) {
    var a, b;
    b = c.split(" ");
    c = b[1] + " " + b[2] + ", " + b[5] + " " + b[3];
    a = Date.parse(c);
    b = (arguments_.length > 1 ? arguments_[1] : new Date);
    a = parseInt((b.getTime() - a) / 1e3, 10);
    a += b.getTimezoneOffset() * 60;
    if (a < 60) {
      return "less than a minute ago";
    } else {
      if (a < 120) {
        return "about a minute ago";
      } else {
        if (a < 3600) {
          return parseInt(a / 60, 10).toString() + " minutes ago";
        } else {
          if (a < 7200) {
            return "about an hour ago";
          } else {
            if (a < 86400) {
              return "about " + parseInt(a / 3600, 10).toString() + " hours ago";
            } else {
              if (a < 172800) {
                return "1 day ago";
              } else {
                return parseInt(a / 86400, 10).toString() + " days ago";
              }
            }
          }
        }
      }
    }
  };

  jQuery(document).ready(function($) {
    return $.getJSON("http://api.twitter.com/1/statuses/user_timeline.json?include_rts=true&screen_name={{ site.twitter.username }}&count={{ site.twitter.count }}&callback=?", function(c) {
      var a, b, e, f;
      b = [];
      a = 0;
      while (a < c.length) {
        e = c[a].user.screen_name;
        f = c[a].text.replace(/((https?|s?ftp|ssh)\:\/\/[^"\s\<\>]*[^.,;'">\:\s\<\>\)\]\!])/g, function(d) {
          return "<a href=\"" + d + "\">" + d + "</a>";
        }).replace(/\B@([_a-z0-9]+)/g, function(d) {
          return d.charAt(0) + "<a href=\"http://twitter.com/" + d.substring(1) + "\">" + d.substring(1) + "</a>";
        });
        b.push("<li><span class=\"status\">" + f + "</span> <a class=\"time\" href=\"http://twitter.com/" + e + "/statuses/" + c[a].id + "\">" + relative_time(c[a].created_at) + "</a></li>");
        a++;
      }
      return document.getElementById("tweets").innerHTML = b.join("");
    });
  });

}).call(this);
