import { test, expect } from '@playwright/test';
import { waitForPageReady } from './helpers';

test.describe('Post Images', () => {
  // Test posts that have images in front matter
  const postsWithImages = [
    '/2015/04/22/the-difference-between-18f-and-usds/',
    '/2019/02/06/open-source-legal-workflows/',
    '/2019/07/18/a-community-of-communities-oscon-2019/',
    '/2020/01/02/resolutions-for-sustaining-and-growing-open-source-communities/',
  ];

  postsWithImages.forEach((postUrl) => {
    test(`${postUrl} should NOT render image in visual output`, async ({ page }) => {
      await page.goto(postUrl);
      await waitForPageReady(page);

      // Check that there are no images in the post header
      const headerImages = page.locator('.post-header img, header.post-header img');
      const headerImageCount = await headerImages.count();
      expect(headerImageCount).toBe(0);

      // More broadly, ensure no images with post-image class exist
      const postImages = page.locator('.post-image');
      const postImageCount = await postImages.count();
      expect(postImageCount).toBe(0);
    });

    test(`${postUrl} should have image in OG metadata`, async ({ page }) => {
      await page.goto(postUrl);
      await waitForPageReady(page);

      // Check for Open Graph image tag (required)
      const ogImage = page.locator('meta[property="og:image"]');
      await expect(ogImage).toHaveCount(1);
      
      const ogImageContent = await ogImage.getAttribute('content');
      expect(ogImageContent).toBeTruthy();
      expect(ogImageContent!.length).toBeGreaterThan(0);

      // Check for Twitter Card image tag (Jekyll SEO tag uses property attribute)
      const twitterImage = page.locator('meta[property="twitter:image"]');
      await expect(twitterImage).toHaveCount(1);
      
      if (twitterImageCount > 0) {
        const twitterImageContent = await twitterImage.getAttribute('content');
        expect(twitterImageContent).toBeTruthy();
        expect(twitterImageContent!.length).toBeGreaterThan(0);
      }
    });
  });

  test('Post without image should use default OG image', async ({ page }) => {
    // Use a post without an image in front matter
    await page.goto('/2015/12/08/types-of-pull-requests/');
    await waitForPageReady(page);

    // Should still have OG image metadata (dynamic OG image or default headshot)
    const ogImage = page.locator('meta[property="og:image"]');
    await expect(ogImage).toHaveCount(1);
    
    const ogImageContent = await ogImage.getAttribute('content');
    expect(ogImageContent).toBeTruthy();
    
    // Astro generates dynamic OG images for posts (at /og/...), or uses default headshot
    const validOgImagePatterns = [
      '/og/',           // Dynamic OG images generated by Astro
      'headshot',       // Default headshot image
      '/assets/img/',   // Assets directory
    ];
    const hasValidPattern = validOgImagePatterns.some(pattern => 
      ogImageContent!.includes(pattern)
    );
    expect(hasValidPattern).toBeTruthy();
  });
});
