#!/bin/sh
#bootstrap the development environment

set -e

echo "cloning into submodules"
git submodule init
git submodule update

echo "Bundle Installin'"
gem install bundler
bundle install

echo "NPM installin"
nodenv exec npm install
nodenv npm install grunt-cli -g