#!/bin/sh

set -e

echo "Cleaning up..."
rm -Rf _site

echo "building assets"
grunt

echo "building contributors"
ruby script/contributors.rb

echo "building site"
jekyll build -c _config.yml,_config_local.yml