#!/bin/sh

set -e

echo "Cleaning up..."
rm -Rf _site

echo "building assets"
exec grunt

echo "building contributors"
bundle exec ruby script/contributors.rb

echo "building site"
bundle exec jekyll build

echo "built"