#!/bin/sh

set -e

export CI=1
script/branding

script/title "building assets"
npm run build

script/title "checking Astro types"
npm run astro:check

script/title "building Astro site"
npm run astro:build

script/title "checking js"
npm run lint-js

script/title "checking json"
npm run lint-json

script/title "checking yaml"
npm run lint-yaml

script/title "Cleaning up..."
rm -Rf dist-astro
