#!/bin/sh

set -e

title () {
  echo ""
  echo "-------------------------------"
  echo $1
  echo "-------------------------------"
  echo ""
}

export CI=1
script/branding

title "checking markdown"
script/remark

title "checking site"
bundle exec rake test

title "checking DNS"
bundle exec github-pages health-check

title "Cleaning up..."
rm -Rf _site
