#!/bin/sh

set -e

title () {
  echo ""
  echo "-------------------------------"
  echo "$1"
  echo "-------------------------------"
  echo ""
}

export CI=1
script/branding

title "checking markdown"
script/remark

title "checking text"
script/lint-text

title "checking vale"
script/vale

title "checking site"
bundle exec rake test

title "checking ruby"
bundle exec rubocop -D -S

title "checking js"
npm run lint-js

title "checking json"
npm run lint-json

title "checking yaml"
npm run lint-yaml

title "checking front matter"
bundle exec script/lint-front-matter

title "checking DNS"
bundle exec github-pages health-check

title "Cleaning up..."
rm -Rf _site
