#!/usr/bin/env ruby
# frozen_string_literal: true

require 'github-pages-health-check'

cname_path = File.expand_path 'CNAME', Dir.pwd
raise 'No CNAME file found in current directory' unless File.exist?(cname_path)

cname = File.read(cname_path).strip
check = GitHubPages::HealthCheck.check(cname)
puts "Checking domain #{cname}..."

if check.valid?
  puts 'Everything looks a-okay! :)'
  exit 0
else
  puts "Uh oh. Looks like something's fishy: #{check.reason}"
  exit 1
end
