#!/bin/sh
# Creates a new post with today's date
# Usage: script/new [post-slug]

set -e

date=$(date +"%Y-%m-%d")
file="_posts/$date-$1.md"
title=$(echo "$1" | sed s/-/\ /g)

git checkout -B $1

touch "$file"
echo "---\ntitle: $title\ndescription:\n---\n\n" > $file

git add "$file"
git commit -m "Create $file"

atom pwd "$file"
