#!/bin/sh
# Creates a new post with today's date
# Usage: script/new [post-slug]

date=$(date +"%Y-%m-%d")
file="_posts/$date-$1.md"
touch "$file"
echo "---\ntitle:\ndescription:\n---\n\n" > $file
atom pwd "$file"
