#!/bin/sh

set -e

# http://stackoverflow.com/questions/2657935/checking-for-a-dirty-index-or-untracked-files-with-git
function git_dirty {
  [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]] && return 1
}

if git_dirty > 0; then
  echo "Nothing to commit. Bailing."
  exit 0
fi

echo "git is dirty... we're in business."

git add .
git commit -m "[Jekyllbot] Automated build."
git push