#!/bin/sh

set -e

# http://stackoverflow.com/questions/2657935/checking-for-a-dirty-index-or-untracked-files-with-git
if test -z "$(git status --porcelain)"; then
  echo "Nothing to commit. Bailing."
  exit
fi

echo "git is dirty... we're in business."

git add .
git commit -m "[Jekyllbot][ci skip] Automated build."
git push